//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeRenovtors.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeRenovatorsEntities : DbContext
    {
        public HomeRenovatorsEntities()
            : base("name=HomeRenovatorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<QueryDetail> QueryDetails { get; set; }
        public virtual DbSet<ServiceDetail> ServiceDetails { get; set; }
        public virtual DbSet<SkilledLabourDetail> SkilledLabourDetails { get; set; }
        public virtual DbSet<StaffDetail> StaffDetails { get; set; }
    }
}
